typeset -gA FISH_ABBREVIATIONS
FISH_ABBREVIATIONS=(
  g git
  gst 'git status'
  gl 'git pull'
  gp 'git push'
  gc 'git commit -v'
  'gc!' 'git commit -v --amend'
  gca 'git commit -v -a'
  'gca!' 'git commit -v -a --amend'
  gcm 'git commit -m'
  gcam 'git commit -a -m'
  gb 'git branch'
  gba 'git branch -av'
  gm 'git merge'
  grs 'git restore'
  grst 'git restore --staged'
  gsta 'git stash'
  gstl 'git stash list'
  gstp 'git stash pop'
  gstd 'git stash drop'
  gsts 'git stash show --text'
  k kubectl
  kaf 'kubectl apply -f'
  keti 'kubectl exec -ti'
  kcuc 'kubectl config use-context'
  kcsc 'kubectl config set-context'
  kcdc 'kubectl config delete-context'
  kccc 'kubectl config current-context'
  kcsccn 'kubectl config set-context --current --namespace'
  kcgc 'kubectl config get-contexts'
  kdel 'kubectl delete'
  kdelf 'kubectl delete -f'
  kgp 'kubectl get pods'
  kgpa 'kubectl get pods --all-namespaces'
  kgpw 'kubectl get pods --watch'
  kgpwide 'kubectl get pods -o wide'
  kep 'kubectl edit pods'
  kdp 'kubectl describe pods'
  kdelp 'kubectl delete pods'
  kgpl 'kubectl get pods -l'
  kgpn 'kubectl get pods -n'
  kgs 'kubectl get svc'
  kgsa 'kubectl get svc --all-namespaces'
  kgsw 'kubectl get svc --watch'
  kgswide 'kubectl get svc -o wide'
  kes 'kubectl edit svc'
  kds 'kubectl describe svc'
  kdels 'kubectl delete svc'
  kgi 'kubectl get ingress'
  kgia 'kubectl get ingress --all-namespaces'
  kei 'kubectl edit ingress'
  kdi 'kubectl describe ingress'
  kdeli 'kubectl delete ingress'
  kgh 'kubectl get httproute'
  kgha 'kubectl get httproute --all-namespaces'
  keh 'kubectl edit httproute'
  kdh 'kubectl describe httproute'
  kdelh 'kubectl delete httproute'
  kgg 'kubectl get grpcroute'
  kgga 'kubectl get grpcroute --all-namespaces'
  keg 'kubectl edit grpcroute'
  kdg 'kubectl describe grpcroute'
  kdelg 'kubectl delete grpcroute'
  kgr 'kubectl get referencegrant'
  kgra 'kubectl get referencegrant --all-namespaces'
  ker 'kubectl edit referencegrant'
  kdr 'kubectl describe referencegrant'
  kdelr 'kubectl delete referencegrant'
  kgns 'kubectl get namespaces'
  kens 'kubectl edit namespace'
  kdns 'kubectl describe namespace'
  kdelns 'kubectl delete namespace'
  kgcm 'kubectl get configmaps'
  kgcma 'kubectl get configmaps --all-namespaces'
  kecm 'kubectl edit configmap'
  kdcm 'kubectl describe configmap'
  kdelcm 'kubectl delete configmap'
  kgsec 'kubectl get secret'
  kgseca 'kubectl get secret --all-namespaces'
  kdsec 'kubectl describe secret'
  kdelsec 'kubectl delete secret'
  kgd 'kubectl get deployment'
  kgda 'kubectl get deployment --all-namespaces'
  kgdw 'kubectl get deployment --watch'
  kgdwide 'kubectl get deployment -o wide'
  ked 'kubectl edit deployment'
  kdd 'kubectl describe deployment'
  kdeld 'kubectl delete deployment'
  ksd 'kubectl scale deployment'
  krsd 'kubectl rollout status deployment'
  kgrs 'kubectl get rs'
  krh 'kubectl rollout history'
  kru 'kubectl rollout undo'
  krr 'kubectl rollout restart'
  kgss 'kubectl get statefulset'
  kgssa 'kubectl get statefulset --all-namespaces'
  kgssw 'kubectl get statefulset --watch'
  kgsswide 'kubectl get statefulset -o wide'
  kess 'kubectl edit statefulset'
  kdss 'kubectl describe statefulset'
  kdelss 'kubectl delete statefulset'
  ksss 'kubectl scale statefulset'
  krsss 'kubectl rollout status statefulset'
  kpf 'kubectl port-forward'
  kga 'kubectl get all'
  kgaa 'kubectl get all --all-namespaces'
  kl 'kubectl logs'
  kl1h 'kubectl logs --since 1h'
  kl1m 'kubectl logs --since 1m'
  kl1s 'kubectl logs --since 1s'
  klf 'kubectl logs -f'
  klf1h 'kubectl logs --since 1h -f'
  klf1m 'kubectl logs --since 1m -f'
  klf1s 'kubectl logs --since 1s -f'
  kcp 'kubectl cp'
  kgno 'kubectl get nodes'
  keno 'kubectl edit node'
  kdno 'kubectl describe node'
  kdelno 'kubectl delete node'
  kgpvc 'kubectl get pvc'
  kgpvca 'kubectl get pvc --all-namespaces'
  kgpvcw 'kubectl get pvc --watch'
  kepvc 'kubectl edit pvc'
  kdpvc 'kubectl describe pvc'
  kdelpvc 'kubectl delete pvc'
  kgds 'kubectl get ds'
  kgdsa 'kubectl get ds --all-namespaces'
  kgdsw 'kubectl get ds --watch'
  keds 'kubectl edit ds'
  kdds 'kubectl describe ds'
  kdelds 'kubectl delete ds'
  kgcj 'kubectl get cronjob'
  kgcja 'kubectl get cronjob --all-namespaces'
  kgcjw 'kubectl get cronjob --watch'
  kecj 'kubectl edit cronjob'
  kdcj 'kubectl describe cronjob'
  kdelcj 'kubectl delete cronjob'
  kgj 'kubectl get job'
  kgja 'kubectl get job --all-namespaces'
  kgjw 'kubectl get job --watch'
  kcjj 'kubectl create job --from=cronjob/'
  kej 'kubectl edit job'
  kdj 'kubectl describe job'
  kdelj 'kubectl delete job'
  kge 'kubectl get events'
  kgea 'kubectl get events --all-namespaces'
  kgew 'kubectl get events --watch'
  d docker
  dc 'docker compose'
  grpc 'grpcurl -plaintext'
)
