"" Initialization
set nocompatible 		" choose no compatibility with legacy vi
call pathogen#infect() 		" load pathogen
call pathogen#helptags()        " load pathogen helptags
let mapleader = ","             " change modifier key to space

"" Misc
set encoding=utf-8
set showcmd                     " display incomplete commands
set hidden                      " Allows vim to handle multiple buffers more efficiently
set number                      " Shows line number
set laststatus=2                " Show status line
filetype plugin indent on       " load file type plugins + indentation
syntax enable

let g:loaded_netrwPlugin=1      " disable netrw plugin
let g:Powerline_symbols='fancy' " enable powerline plugin

"" Theme
colorscheme jellybeans 

"" CtrlP
let g:ctrlp_map = '<C-p>'
let g:ctrlp_cmd = 'CtrlP'

"" Mappings
map <F2> 	:NERDTreeToggle<CR>
map <C-s> 	:Scratch<CR>

"" Whitespace
set nowrap                      " don't wrap lines
set backspace=indent,eol,start  " backspace through everything in insert mode

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

"" GUI
set guioptions-=T               " Toggle off toolbar
set guifont=Monaco\ for\ Powerline:h12

highlight SpellBad term=underline gui=undercurl guisp=Orange
