!/bin/bash
dropboxd &
mpd &
#compton -cGb &
sh ./.fehbg &

xsetroot -cursor_name left_ptr  
setxkbmap -layout no 

DEFAULT_SESSION=spectrwm

case $1 in
spectrwm)
    exec dbus-launch spectrwm
    ;;
xmonad)
    compton -cGb &
    exec ck-launch-session dbus-launch xmonad
    ;;
dwm)
    exec dwm
    ;;
*)
    exec $DEFAULT_SESSION
    ;;
esac
