import = [
  "~/.config/alacritty/gruvbox-material-dark-medium.toml"
]

[font]
size = 16
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[window]
option_as_alt = "OnlyLeft"
# padding = { x = 5, y = 0 }
