import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 15

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"
option_as_alt = "Both"

[window.padding]
x = 0
y = 0
